spring.application.name=emissions-calculator

# PostgreSQL / PostGIS Database Configuration (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/spire_db
spring.datasource.username=spire_user
spring.datasource.password=spire_password
spring.datasource.driverClassName=org.postgresql.Driver

# JPA & Hibernate Spatial Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# External APIs
tfl.api.url=https://api.tfl.gov.uk/AirQuality