spring.application.name=emissions-calculator

# PostgreSQL / PostGIS Database Configuration (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/spire_db
spring.datasource.username=spire_user
spring.datasource.password=spire_password
spring.datasource.driverClassName=org.postgresql.Driver

# JPA & Hibernate Spatial Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# External APIs
tfl.api.url=https://api.tfl.gov.uk/AirQuality

# === NOVO: Configuração do Mirror do OpenStreetMap para evitar timeouts ===
osm.overpass.url=https://overpass.kumi.systems/api/interpreter

spring.jackson.mapper.accept-case-insensitive-enums=true

# ==========================================
# CONFIGURACOES DE LOG E DEBUG DE ERROS
# ==========================================
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.uk.org.spire.emissionsCalculator=OFF
logging.level.org.springframework.web=OFF
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG